{
    "name": "Purchase +",
    "version": "1.0.0",
    "depends": ["purchase", "purchase_igaser", "product"],
    "author": "ABID Makram & ANWAR Othmane",
    "category": "Purchase Management",
    "init_xml": [],
    "data": [
      "security/groups.xml",
      "security/ir.model.access.csv",
      "wizard/purchase_verification.xml",
      "wizard/purchase_request_line_make_purchase_order_view.xml",
      "wizard/request_price_comparison_view.xml",
      "wizard/purchase_entry_wizard.xml",
      "wizard/purchase_order_validation_wizard.xml",
      "wizard/decompte_confirmation_wizard.xml",
      "wizard/stock_backorder_confirmation_message.xml",
      "wizard/backorder_confirmation_inherit_custom.xml",
      # # "wizard/purchase_verification_avance.xml",
      "views/prl_view_tree_purchase_verification.xml",
      "views/purchase_order.xml",
      "views/purchase_request_line_state.xml",
      "views/purchase_request_line.xml",
      "views/purchase_order_line_detail.xml",
      "views/purchase_order_line_attachment.xml",
      "views/purchase_entry_tree.xml",
      "views/purchase_entry_form.xml",
      "views/purchase_entry_decompte_form.xml",
      "views/purchase_entry_decompte_tree.xml",
      "views/purchase_order_line_detail_readonly.xml",
      "views/purchase_order_avance_wizard.xml",
      "views/purchase_order_return_of_guarantee_wizard.xml",
      "views/purchase_entry_decompte_readonly.xml",
      "views/purchase_entry_readonly.xml",
      "views/attachement.xml",
      "views/detail.xml",
      "views/purchase_entry_decompte_final_tree.xml",
      "views/decompt.xml",
      "views/purchase_entry_line_detail.xml",
      "views/purchase_cleaning.xml",
      "views/all.xml",
      "views/actions.xml",
      "views/menus.xml",
      # "static/src/xml/purchase_plus.xml",
    ],
    "demo_xml": [],
    "installable": True,
    "active": False,
}