from . import product
from . import hr
from . import user
from . import purchase
from . import stock
from . import ir_attachment
from . import building_resource
from . import building_resource_config
from . import building_price_calculation
from . import building_order
from . import building_caution
from . import building_attachment
from . import building_subcontracting
from . import building_site
from . import invoice
from . import account_move
from . import building_site_report
from . import vehicle
from . import uom_uom
from . import building_profile_assignment
from . import product_buyer
from . import maintenance_request_resource_material