{
    "name": "Inventaire +",
    "version": "1.0.0",
    "depends": ["stock", "purchase_igaser"],
    "author": "ABID Makram & ANWAR Othmane",
    "category": "Inventaire",
    "data": [
        "security/ir.model.access.csv", 
        "wizard/stock_return_picking_form_view.xml",
        "wizard/stock_picking_transfer_group.xml",
        "wizard/stock_inventory_wizard.xml",
        "wizard/dashboard_stock_wizard.xml",
        "views/stock_picking_transfer.xml",
        "views/building_site.xml",
        "views/stock_warehouse.xml",
        "views/stock_location.xml",
        "views/stock_picking_type.xml",
        "views/product_template.xml",
        "views/stock_picking_outgoing_report.xml",
        "views/stock_move.xml",
        "views/stock_picking_transfer_report.xml",
        # # "views/stock_outing.xml",
        "views/stock_dashboard.xml",
        "views/stock_quant.xml"
        # "static/src/xml/stock_plus.xml",
    ],
    "installable": True,
    "application": True,
    "active": False,
}