{
    'name': 'Logistique',
    'version': '18.0.0.0',
    'summary': 'Logistics operations management',
    'description': 'This module helps manage logistics operations such as vehicles, drivers, and transport orders.',
    'author': 'JAFA Rachid',
    'category': 'Logistic',
    'depends': [
        'base',
        'stock',
        'purchase',
        'sale',
        'fleet',
        'purchase_request',
        'purchase_igaser',
        'building',
    ],
    'data': [
        'security/groups.xml',
        'views/logistic_purchase_request_view_form.xml',
        'views/logistic_product_template_view_form.xml',
        'views/view_purchase_order_tree.xml',
        'views/product_template_search_view_inherit.xml',
        'views/incident_materiel_views.xml',
        'views/actions.xml',
        'views/menus.xml',
        # "static/src/css/style.xml",
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
