{
    "name": "Accounting",
    "version": "14.0.0",
    "category": "Accounting",
    "sequence": 14,
    "author":  "ANWAR Othmane & ABID Makram",
    "license": "AGPL-3",
    "description": "Accounting",
    "depends": ["base", "account", "building"],
    "data": [
        "security/ir.model.access.csv",
        "views/accounting_report.xml",
        "views/report_imputation.xml",
        "views/facture_client_report.xml",
        "views/facture_client.xml",
        "views/ordre_virement_report.xml",
        "views/ordre_virement.xml",
        "views/account_move_view_inherit.xml",
        "views/building_site_view_inherit.xml",
        "views/decompte_provisional_report.xml",
        "views/decompte.xml",
        "wizard/bilan.xml",
        "wizard/resultat.xml",
        "wizard/balance_comptable.xml",
        # # "wizard/balance_tiers.xml",
        # # "wizard/esg.xml",
        # # "wizard/cpc.xml",
        # # "wizard/global_payroll_xlsx.xml",
    ],
    "installable": True,
    "auto_install": False,
    "application": False,
}