{
    "name": "Affectation RH",
    "version": "18.0.0.0",
    "depends": ["building", "purchase_request"],
    "author": "ANWAR Othmane & ABID Makram",
    "category": "HR",
    "description": """""",
    "data": [
        # "static/assets_backend.xml",
        "security/groups.xml",
        "security/ir.model.access.csv",
        "views/hr_assignment_request.xml",
        "views/hr_assignment_request_line.xml",
        "views/hr_assignment.xml",
        "views/hr_assignment_line_view.xml",
        "views/time_machine.xml",
        "views/hr_employee.xml",
        "views/menus.xml",
        "views/hr_assignment_timeclock_line_updated.xml",
        "views/hr_assignment_timeclock_line_updated_view.xml",
        "wizard/hr_assignment_wizard.xml",
        "wizard/hr_assignment_line_reject_reason_wizard.xml",
    ],
    "installable": True,
    "application": True,
    "active": False,
}